### ISSUE TITLE
New ENTRY makes the webpage oversize

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/OpenGraph#12]
Having too many ENTRYs (for me it is 6) makes the webpage think there is more things, when there isn't. Making it float sounds like the best route, but all the stuff gets compressed

**Comment by pgonzbecer** [comment]
Also the .entry css has it's position to relative and setting it to absolute compresses everything for some reason, and it seems that that is correlated with this bug.

**Comment by johnRedden** [comment]
I streamlined the css a bit... this is not something that is easy to do.

**Comment by pgonzbecer** [comment]
I don't know how you did it, but we are able to absolute the thing, no more strange bug
