### ISSUE TITLE
Paper Control Docking

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#2]
Create a wrapper for the paper controls (zooming buttons) and add a button that docks it to the right of the screen window in a clean manner.

**Comment by johnRedden** [comment]
Still need it to be draggable or animate to the edge.

**Comment by pgonzbecer** [comment]
Alright! now lets get this show on the road, I was going to work on that after the collapsing container got done with and I messed with some github stuff

**Comment by johnRedden** [comment]
Maybe add bootstrap class "pull-right" to that collapsing button when
collapsed.. Can you make the width a little less... it is too wide.

[image: Inline image 1]

**Comment by johnRedden** [comment]
The changes made it to my hardDrive... we are working together!  So easy.

Here is what I have so far:
[image: Inline image 1]

I not so darn fast.

**Comment by pgonzbecer** [comment]
Almost got it done, just the entries now

**Comment by johnRedden** [comment]
For collapsable entries... could look like this:
![image](https://cloud.githubusercontent.com/assets/4535729/8112273/aac52d32-101b-11e5-928e-63eabc5b168c.png)

Maybe on showColor double click... toggle the view.

**Comment by johnRedden** [comment]
Actually, showColor on move left dock ... on move right undock.  Click changes the color. 

http://www.smashingmagazine.com/2015/03/20/better-browser-input-events/

**Comment by pgonzbecer** [comment]
done I believe?
