### ISSUE TITLE
Left Listbox or Animate left?

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#21]
I like animate left a little better... the list box kept things tidy but required new divs to be added and kept straight.  Also, why not use Bootstrap btn btn-default in the Entry?  Everything uses bootstrap anyway?  Also, fast or slow... not sure what looks better.  This needs clean up.

**Comment by johnRedden** [comment]
Paul, help decide and then close this.

**Comment by pgonzbecer** [comment]
Sorry got busy these couple of days, Looks as if we are going to go with the animate left, looks nicer and feels better. But I just do not like that overlap thing.
