### ISSUE TITLE
Line Implementation is fragile

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#24]
Cannot type after backspacing lineAB... also need to streamline the logic to make this happen.  Once we get this nice and clean ... same implementation for circleAB... two points determine a circle (center and point on circle).  Clean and fix line first!

**Comment by pgonzbecer** [comment]
I don't have any trouble with it typing after backspacing

**Comment by johnRedden** [comment]
You know... there are only TWO people in all of Tulare County that can
appreciate this!

**Comment by pgonzbecer** [comment]
Really? Who?

**Comment by pgonzbecer** [comment]
Not sure if this is a problem??

**Comment by pgonzbecer** [comment]
Ok nevermind, im starting to experience this now, but not for the line. It seems as if the entry is loosing focus or something when you hit the very back of the textbox

**Comment by johnRedden** [comment]
?? not understanding the issue??

**Comment by pgonzbecer** [comment]
I suppose I have to show you in person about this issue

**Comment by pgonzbecer** [comment]
Haha accidentally closed it

**Comment by johnRedden** [comment]
I am closing this... I think the line is robust now?
