### ISSUE TITLE
Vertical Line

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#25]
Graph vertical lines x = 2 ... right now this entry gives incorrect results.  Catch "x = "  on input and do not allow it.... only allow x = number and plot a vertical line.

**Comment by pgonzbecer** [comment]
Ref: http://jsxgraph.uni-bayreuth.de/wiki/index.php/Change_Equation_of_a_Graph#JavaScript_Part

> //glider on the curve
> **p1** = board.create('glider', [0,0,graph], {style:6, name:'P'});
> //define the derivative of f
> g = JXG.Math.Numerics.D(f);
> //a point on the tangent
> //                                 variable x coordinate           variable y coordinate depending on the derivative of f at point p1.X()
> **p2** = board.create('point', [function() { return p1.X()+1;}, function() {return p1.Y()+JXG.Math.Numerics.D(graph.Y)(p1.X());}], {style:1, name:''});
> //the tangent 
> **l1 = board.create('line', [p1,p2],{});**

The highlighted ones are key, just get two points from the 'x=' and create a line.

NOTE: I will be going to work soon, so this is more of a self reminder than a request/command

**Comment by johnRedden** [comment]
No... you can graph a vertical line using the line funtion in JSXGraph...
using parameters for ax+by+cz=0... I just need to find the documentation.

**Comment by johnRedden** [comment]
Vertical line implemented here [z, a, b] for the parameters... x = 3 corresponds to [-3, 1, 0]  seems strange but that is how.

http://jsxgraph.uni-bayreuth.de/wiki/index.php/Aligning_text
