### ISSUE TITLE
Map points are weird with 3 parameters

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/OpenGraph#26]
If you type in (a, b, c), given that a, b, and c are constants, it doesn't graph it in a 3d space flattened to a 2d graph, but does something rather peculiar. I don't know what it does, but it's weird. Its not game breaking, but its a bug nonetheless.

**Comment by johnRedden** [comment]
I guess we catch the second comma and disable typing from that point on.  Not allow it to be typed for now.  3D graph is insane.

http://dlippman.imathas.com/3dg/index.html

Don't even think about it... we need to get this going first!

**Comment by pgonzbecer** [comment]
err irrelevent now with the new mathquill in place??
