### ISSUE TITLE
Re-render line after points have changed

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/OpenGraph#27]
The line disappears whenever one of the points have changed

**Comment by johnRedden** [comment]
This is correct?  ... two points determine a line... so if one is deleted
the line should disappear.

**Comment by pgonzbecer** [comment]
Changed, not deleted. If you change point A from (7,0) to (7,1) then it moves the map point, but doesnt re-render the line

**Comment by johnRedden** [comment]
yeah, I see... you have to give the lineAB focus again and hit space.  That will be hard to fix... not sure if the effort is worth the fix... user will have to deal with that.

**Comment by pgonzbecer** [comment]
No longer will the user have to deal with that! It was a relatively simple fix, should work for even map points too

**Comment by johnRedden** [comment]
Issue is back... it was deleting map points for conics but not regular graphs.  I have no idea why?

**Comment by johnRedden** [comment]
issue magically resolved!
