### ISSUE TITLE
Strange Fraction Behavior

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#39]
Type in 1/ x-3 and the text box wraps and does not expand on the bottom.  

I addressed this issue before, but I forgot how I fixed it in mathquill.css??  or somewhere else.

**Comment by johnRedden** [comment]
There is a fake cursor produced in the css...  it is wrapping below when fraction.  This is a css problem for sure.

**Comment by pgonzbecer** [comment]
I think I got it done? It was weird, the width of the denominator was the problem, so I took it out and it looks like that did the trick

**Comment by pgonzbecer** [comment]
https://github.com/johnRedden/OpenGraph/issues/45 just opened a whole can of worms that I didn't even notice. Try making all of x^2+3x+4 into a fraction with something else, gives undesired results. I think the trick I did only worked for single coefficients / x. This topic still needs work gah.

**Comment by johnRedden** [comment]
I put the width back to 100% and fixed the single fraction denominator issue with:

white-space:nowrap;

However, when using parentheses (x-2)/   The goofup remains.  I wonder if the original mathquill-basic.css did this or if it is something I did?

**Comment by johnRedden** [comment]
This may not be a CSS issue... the fraction is being created under the parenthesis ')/x'

![image](https://cloud.githubusercontent.com/assets/4535729/8393061/6d1f0724-1cb3-11e5-8b6c-2606d52e422a.png)

Most likely a programmatic fix... if parenthesis fraction over whole group.

**Comment by johnRedden** [comment]
Fixed by way of magik!!!   I just needed to refresh... sometimes my chrome browser does not refresh when css changes??  I think all is well... please test and then close.  HIT REFRESH or try a different browser.

**Comment by pgonzbecer** [comment]
Alright! Looks completely fine to me, Great Job!
