### ISSUE TITLE
Vertical Line

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#42]
A user types in 'x=' and you know it is going to be a vertical line.  (no functions of y yet.)

So x = 3.5 or x=3/4 or x=sqrt(2)...  whatever number the user types after the '=' is the number.

```
// For vertical line at x=3  where ax+by+cz=0  => [z,a,b] goofyness
brd.create('line', [-3, 1, 0], {strokeWidth:1, dash:2});  
```

**Comment by pgonzbecer** [comment]
done son
