### ISSUE TITLE
Overlapping Entries

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#43]
When two entries overlap... the entry gaining focus should be z-indexed to the top.

**Comment by pgonzbecer** [comment]
They should be working right, the only real problem is CSS, the buttons are floating, which the only real thing that detected as wrapped by the entry is the math-input

**Comment by pgonzbecer** [comment]
*.math-field, sorry

**Comment by johnRedden** [comment]
Looks good to me.
