### ISSUE TITLE
Vertical Lines are Draggable

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#52]
Vertical lines labelled x = 3 should be fixed.  Just a matter of create settings.

**Comment by johnRedden** [comment]
the attribute is 'fixed'  boolean for draggable lines.

BUT, I thought it would be cool to have movable vertical lines (for the THE VLT TEST !!)  Fixed vertical lines can be graphed using two points.  SO....  when a vertical line x = 3 is dragged.. the mathinput should update to reflect the change.  There are issues, I tried to comment:
![image](https://cloud.githubusercontent.com/assets/4535729/8413181/833611d8-1e43-11e5-90b6-67e0076deca1.png)

HELP.

**Comment by johnRedden** [comment]
Oh, if we get this to work for vertical lines... we should be able to do it for horizontal lines.  Just a thought.

**Comment by pgonzbecer** [comment]
done, now all I need is horizontals

**Comment by pgonzbecer** [comment]
I also got horizontal done
