### ISSUE TITLE
Ellipse and Hyperbola ABC

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#53]
Hell, why not add ellipse ABC and hyperbola ABC??  ABC = [focus, focus, point]

http://jsxgraph.uni-bayreuth.de/docs/symbols/Ellipse.html

http://jsxgraph.uni-bayreuth.de/docs/symbols/Hyperbola.html

**Comment by pgonzbecer** [comment]
done, just keep these coming, I think I got a system down for super easy implementations
