### ISSUE TITLE
Points are static

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/OpenGraph#55]
Should points be static, or be able to move dynamically? Of course they should be able to change the entry's entry.

**Comment by johnRedden** [comment]
Uhhh, I like that you ask this question... basically, we can do anything we want!!  My thought right now is that they should be static.  Plot a point (3,2) and that is what you get.

**Comment by johnRedden** [comment]
Ahh... I think I get what you are thinking... we can obtain dynamic graphs with a little bit of creative map point work:
![image](https://cloud.githubusercontent.com/assets/4535729/8423686/1a761490-1ea2-11e5-92c8-e97b1df41627.png)

Map points are dynamic... create conics using map points and we have dynamics.

https://rawgit.com/johnRedden/OpenGraph/master/opengraph.html?x-1&-x&ellipse%5C%20abc

create the map points on the link and then ellipse will render. When I hit the share button that link should automatically highlight for me!!

**Comment by pgonzbecer** [comment]
So no? At least for now?
