### ISSUE TITLE
Parabolas are weird to construct

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/OpenGraph#56]
Parabolas require a line on the board in order for them to properly be constructed:
http://jsxgraph.uni-bayreuth.de/docs/symbols/Parabola.html
Not sure how that will work for the user

**Comment by johnRedden** [comment]
Two points B and C are already created by the user... create a line:
   var userLine = board.create('line', [B,C]);
Then use this new userLine to create the Parabola where A is the focus.
  var parab = board.create('parabola',[A,userLine]);

**Comment by johnRedden** [comment]
Can now graph a parabola.
