### ISSUE TITLE
Entry z-index to Top

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#6]
Need to change zindex to place an ENTRY at the top level when clicked on.  There is a utility in JQuery UI that might help with this.

**Comment by pgonzbecer** [comment]
What do you mean by this?

**Comment by johnRedden** [comment]
The ENTRY that is clicked should be pushed to the top... sometimes when overlap it is below another entry.

**Comment by pgonzbecer** [comment]
This doesn't look like it is a problem anymore?? I will close it, but if it magically happens again somehow, we should open it back up
