### ISSUE TITLE
Plotting Inequalities

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#68]
Had a request to plot inequalities... y > x + 1.  should be able to:

http://jsxgraph.uni-bayreuth.de/docs/symbols/Inequality.html

// Plot the inequality 
//     y >= 2/3 x + 1 
// or 
//     0 >= -3y + 2x +1
var l = board.create('line', [1, 2, -3]),
    ineq = board.create('inequality', [l], {inverse:true});

**Comment by johnRedden** [comment]
No a fun job... only will work for linears too... I think.

**Comment by pgonzbecer** [comment]
It should be working now, but it is still at it's very most, basic
