### ISSUE TITLE
fractions (math) inside functions

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#77]
fractions ... or trig for that matter not working inside functions.
![image](https://cloud.githubusercontent.com/assets/4535729/8630981/1a93325e-2722-11e5-91e6-c1e6e57477cf.png)

**Comment by johnRedden** [comment]
Can now do math inside functions... but evaluating is broken.  Really seems like it should still work but it needs a space to evaluate.  When its complicated it will not evaluate.
![image](https://cloud.githubusercontent.com/assets/4535729/8631813/04a6e904-2736-11e5-8bfe-fac90c4dfb31.png)

**Comment by johnRedden** [comment]
simple problem can't find it... 4*4 space  (needs the space to evaluate??)
![image](https://cloud.githubusercontent.com/assets/4535729/8631899/4a2ed7ea-2739-11e5-8d63-60af6b399119.png)

**Comment by pgonzbecer** [comment]
You weren't catching the eval method somewhere, silly mistake haha done
