### ISSUE TITLE
xsin(x)  without the * graphs incorrect results

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#79]
xsin(x) graphs incorrect results... also xln(x) and others too.

The issue is the aterisk  x*sin(x)... this is worked before using mquill text because there was an asterisk between each char.  Now... the no \* is the issue.

**Comment by johnRedden** [comment]
I was testing on openGraphingCalculator and not the current GitHub version... this issue has been resolved already.  My error.

**Comment by johnRedden** [comment]
current version still has this problem... issue reopened.

**Comment by pgonzbecer** [comment]
done, although we should find out if there is anything else that has this problem too
