### ISSUE TITLE
Standalone Pi does not evaluate

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#80]
Stand alone pi does not evaluate to but pi -1 does?  Also, functions of pi do evaluate.
![image](https://cloud.githubusercontent.com/assets/4535729/8635172/2d5be304-27cc-11e5-9aca-5ea30c852872.png)

sin(pi) works well
pi^2 is not working at all... got to track this down.

**Comment by johnRedden** [comment]
pi^x does not graph but pi^(x-1) does graph.

**Comment by johnRedden** [comment]
Functions of pi^x graph nicely...
![image](https://cloud.githubusercontent.com/assets/4535729/8635189/265eb648-27cd-11e5-873a-f8170d7f45fa.png)

**Comment by pgonzbecer** [comment]
You just needed to invoke a space for some reason, it should evaluate now
