### ISSUE TITLE
Function Arithmetic

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#82]
I think we should implement function arithmetic...

f(x) + 5  ==> graph
2-g(x) ==> graph
6f(x) ==> graph
g(x)/2 ==> graph

Then think about composition:  f(g(x)) ==> graph

**Comment by pgonzbecer** [comment]
done... sort of, basics is there. it works OK, but still needs some work to be done.

f(x)+5 : Graphs,
2-g(x) : Graphs,
6f(x) : Graphs,
g(x)/2 : Graphs,
f(g(x)) : Graphs,
f(f(x)) : Graphs,
g(f(x)) : Does not Graph

I believe it might the the order in which g and f are found, fix fix fix fix

**Comment by pgonzbecer** [comment]
got g(f(x)) to work but g(g(f(x))) does not work. should we really worry about it??
